name: 사용자 등록
description: "{도메인}/u/{사용자_아이디} 주소 사용을 위한 사용자 등록"
title: "[USER REGISTER] 사용자 등록"
labels: user-register
assignees: OUS-KR
body:
  - type: input
    id: user-id
    attributes:
      label: 사용자 아이디
      description: "`3자리 이상 30자리 이하`의 `영문 소문자 (a-z)`, `숫자 (0-9)`, `하이픈 (-)`, `언더스코어 (_)`로 구성되며, 시작과 끝은 `영어 소문자`와 `숫자`만 가능"
      placeholder: "예: my_user-id"
    validations:
      required: true