name: User register by issue
  
on:
  issues:
    types: [opened, edited]
    
jobs:
  user-register:
    if: contains(github.event.issue.labels.*.name, 'user-register')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        
    - name: Set env
      id: env
      env:
        GITHUB_ID: ${{ github.event.issue.user.id }}
      run: |
        # Created at
        CREATED_AT=$(TZ=Asia/Seoul date +"%Y-%m-%dT%H:%M:%S%:z")
        
        # Env
        ADMIN_GITHUB_ID="210320028"
        USERS_REGISTER_INFO_PATH="registered/users"
        USERS_PUBLIC_PATH="public/u"
        USERS_SERVICE_PATH="u"
        
        USER_REGISTER_INFO_FILE="$USERS_REGISTER_INFO_PATH/${GITHUB_ID}.json"
        USER_HTML_TEMPLATE_FILE="templates/user.html"
        USER_PAGE_HTML_FILE_NAME="index.html"
        USER_META_INFO_FILE_NAME="user.json"
        USER_MENU_INFO_FILE_NAME="menu.json"
        CONTENT_META_INFO_FILE_NAME="content.json"
        LIST_GLOBAL_META_INFO_FILE_NAME="list.global.json"
        
        # Pause register
        if [ "$GITHUB_ID" != "$ADMIN_GITHUB_ID" ]; then
          # exit 1
          echo "-"
        fi
        
        # Github output
        {
          # Created at
          echo "created_at=$CREATED_AT"
          
          # Env
          echo "admin_github_id=$ADMIN_GITHUB_ID"
          echo "users_register_info_path=$USERS_REGISTER_INFO_PATH"
          echo "users_public_path=$USERS_PUBLIC_PATH"
          echo "users_service_path=$USERS_SERVICE_PATH"
          
          echo "user_register_info_file=$USER_REGISTER_INFO_FILE"
          echo "user_html_template_file=$USER_HTML_TEMPLATE_FILE"
          echo "user_page_html_file_name=$USER_PAGE_HTML_FILE_NAME"
          echo "user_meta_info_file_name=$USER_META_INFO_FILE_NAME"
          echo "user_menu_info_file_name=$USER_MENU_INFO_FILE_NAME"
          echo "content_meta_info_file_name=$CONTENT_META_INFO_FILE_NAME"
          echo "list_global_meta_info_file_name=$LIST_GLOBAL_META_INFO_FILE_NAME"
        } >> "$GITHUB_OUTPUT"
        
    - name: Check if user already registered
      id: register-info
      env:
        ENV__USER_REGISTER_INFO_FILE: ${{ steps.env.outputs.user_register_info_file }}
        ENV__ADMIN_GITHUB_ID: ${{ steps.env.outputs.admin_github_id }}
        GITHUB_ID: ${{ github.event.issue.user.id }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Validation: User
        if [ "$GITHUB_ID" != "$ENV__ADMIN_GITHUB_ID" ]; then
          if [ -f "$ENV__USER_REGISTER_INFO_FILE" ]; then
            USER_COUNT=$(jq '.user_ids | length' "$ENV__USER_REGISTER_INFO_FILE")
            echo "USER_COUNT: $USER_COUNT"
            
            if [ "$USER_COUNT" -ge 1 ]; then
              echo "이미 사용자 아이디를 등록한 Github 사용자: **$GITHUB_ID**" > comment.md
              gh issue comment "$ISSUE_NUMBER" -F comment.md
              exit 1
            fi
          fi
        fi
        
    - name: Parse issue forms
      id: issue-parser
      uses: edumserrano/github-issue-forms-parser@v1.3.7
      with:
        template-filepath: '.github/ISSUE_TEMPLATE/01-user-register-by-issue.yml'
        issue-form-body: '${{ github.event.issue.body }}'
        
    - name: Extract user ID from issue body
      id: extract
      env:
        ENV__USERS_PUBLIC_PATH: ${{ steps.env.outputs.users_public_path }}
        ENV__USERS_SERVICE_PATH: ${{ steps.env.outputs.users_service_path }}
        ENV__USER_PAGE_HTML_FILE_NAME: ${{ steps.env.outputs.user_page_html_file_name }}
        ENV__USER_META_INFO_FILE_NAME: ${{ steps.env.outputs.user_meta_info_file_name }}
        ENV__USER_MENU_INFO_FILE_NAME: ${{ steps.env.outputs.user_menu_info_file_name }}
        ENV__CONTENT_META_INFO_FILE_NAME: ${{ steps.env.outputs.content_meta_info_file_name }}
        ENV__LIST_GLOBAL_META_INFO_FILE_NAME: ${{ steps.env.outputs.list_global_meta_info_file_name }}
        PARSED_ISSUE: ${{ steps.issue-parser.outputs.parsed-issue }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract
        USER_ID=$(echo "$PARSED_ISSUE" | jq -r '.["user-id"]')
        
        # Validation: User ID
        if [[ ! "$USER_ID" =~ ^[a-z0-9][a-z0-9_-]{1,28}[a-z0-9]$ ]]; then
          echo "올바르지 않은 아이디 형식" > comment.md
          gh issue comment "$ISSUE_NUMBER" -F comment.md
          echo "user_id=" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        # User paths & files
        USER_PUBLIC_PATH="$ENV__USERS_PUBLIC_PATH/$USER_ID"
        USER_SERVICE_PATH="$ENV__USERS_SERVICE_PATH/$USER_ID"
        
        CONTENT_PUBLIC_META_INFO_FILE="$USER_PUBLIC_PATH/$ENV__CONTENT_META_INFO_FILE_NAME"
        LIST_PUBLIC_GLOBAL_META_INFO_FILE="$USER_PUBLIC_PATH/$ENV__LIST_GLOBAL_META_INFO_FILE_NAME"
        USER_PUBLIC_PAGE_HTML_FILE="$USER_PUBLIC_PATH/$ENV__USER_PAGE_HTML_FILE_NAME"
        USER_PUBLIC_META_INFO_FILE="$USER_PUBLIC_PATH/$ENV__USER_META_INFO_FILE_NAME"
        USER_SERVICE_MENU_INFO_FILE="$USER_SERVICE_PATH/$ENV__USER_MENU_INFO_FILE_NAME"
        
        # SEO
        CANONICAL_PATH="$USER_SERVICE_PATH"
        PAGE_TITLE="$USER_ID"
        PAGE_DESC="${USER_ID}의 개인 페이지"
        
        # Github output
        {
          echo "user_id=$USER_ID"
          
          echo "user_public_path=$USER_PUBLIC_PATH"
          echo "user_service_path=$USER_SERVICE_PATH"
          
          echo "content_public_meta_info_file=$CONTENT_PUBLIC_META_INFO_FILE"
          echo "list_public_global_meta_info_file=$LIST_PUBLIC_GLOBAL_META_INFO_FILE"
          echo "user_public_page_html_file=$USER_PUBLIC_PAGE_HTML_FILE"
          echo "user_public_meta_info_file=$USER_PUBLIC_META_INFO_FILE"
          echo "user_service_menu_info_file=$USER_SERVICE_MENU_INFO_FILE"
          
          echo "canonical_path=$CANONICAL_PATH"
          echo "page_title=$PAGE_TITLE"
          echo "page_desc=$PAGE_DESC"
        } >> "$GITHUB_OUTPUT"
        
    - name: Check if user exists
      uses: ./.github/actions/check-if-user-exists
      with:
        user-public-path: ${{ steps.extract.outputs.user_public_path }}
        user-id: ${{ steps.extract.outputs.user_id }}
        issue-number: ${{ github.event.issue.number }}
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create user page
      env:
        ENV__USER_PUBLIC_PATH: ${{ steps.extract.outputs.user_public_path }}
        ENV__USER_HTML_TEMPLATE_FILE: ${{ steps.env.outputs.user_html_template_file }}
        ENV__USER_PAGE_HTML_FILE_NAME: ${{ steps.env.outputs.user_page_html_file_name }}
        ENV__USER_PUBLIC_PAGE_HTML_FILE: ${{ steps.extract.outputs.user_public_page_html_file }}
        ENV__USER_PUBLIC_META_INFO_FILE: ${{ steps.extract.outputs.user_public_meta_info_file }}
        ENV__USER_SERVICE_MENU_INFO_FILE: ${{ steps.extract.outputs.user_service_menu_info_file }}
        ENV__USERS_REGISTER_INFO_PATH: ${{ steps.env.outputs.users_register_info_path }}
        ENV__USER_REGISTER_INFO_FILE: ${{ steps.env.outputs.user_register_info_file }}
        ENV__CONTENT_PUBLIC_META_INFO_FILE: ${{ steps.extract.outputs.content_public_meta_info_file }}
        ENV__CONTENT_META_INFO_FILE_NAME: ${{ steps.env.outputs.content_meta_info_file_name }}
        ENV__LIST_PUBLIC_GLOBAL_META_INFO_FILE: ${{ steps.extract.outputs.list_public_global_meta_info_file }}
        USER_ID: ${{ steps.extract.outputs.user_id }}
        CANONICAL_PATH: ${{ steps.extract.outputs.canonical_path }}
        PAGE_TITLE: ${{ steps.extract.outputs.page_title }}
        PAGE_DESC: ${{ steps.extract.outputs.page_desc }}
        CREATED_AT: ${{ steps.env.outputs.created_at }}
        GITHUB_ID: ${{ github.event.issue.user.id }}
        GITHUB_NAME: ${{ github.event.issue.user.login }}
      run: |
        # Template
        mkdir -p "$ENV__USER_PUBLIC_PATH"
        envsubst < "$ENV__USER_HTML_TEMPLATE_FILE" > "$ENV__USER_PUBLIC_PAGE_HTML_FILE"
        
        # User meta info
        cat <<EOF > "$ENV__USER_PUBLIC_META_INFO_FILE"
        {
          "github_id": "$GITHUB_ID",
          "github_name": "$GITHUB_NAME",
          "created_at": "$CREATED_AT"
        }
        EOF
        
        # Content meta info
        cat <<EOF > "$ENV__CONTENT_PUBLIC_META_INFO_FILE"
        {
          "type": "user-page",
          "path": "",
          "files": [
            "$ENV__USER_PAGE_HTML_FILE_NAME",
            "$ENV__CONTENT_META_INFO_FILE_NAME"
          ],
          "created_at": "$CREATED_AT"
        }
        EOF
        
        # Global list meta info
        cat <<EOF > "$ENV__LIST_PUBLIC_GLOBAL_META_INFO_FILE"
        {
          "list": [
            {
              "type": "user-page",
              "path": "",
              "files": [
                "$ENV__USER_PAGE_HTML_FILE_NAME",
                "$ENV__CONTENT_META_INFO_FILE_NAME"
              ],
              "created_at": "$CREATED_AT"
            }
          ]
        }
        EOF
        
    - name: Update user register info file
      env:
        ENV__USERS_REGISTER_INFO_PATH: ${{ steps.env.outputs.users_register_info_path }}
        ENV__USER_REGISTER_INFO_FILE: ${{ steps.env.outputs.user_register_info_file }}
        USER_ID: ${{ steps.extract.outputs.user_id }}
      run: |
        # User register info
        mkdir -p "$ENV__USERS_REGISTER_INFO_PATH"
        
        python3 << EOF
        import os
        import json
        
        # Load JSON file
        json_file = os.environ["ENV__USER_REGISTER_INFO_FILE"]
        json_data = {"user_ids": []}
        if os.path.exists(json_file):
          with open(json_file, "r", encoding="utf-8") as f:
            json_data = json.load(f)
            
        # Update JSON data
        user_id = os.environ["USER_ID"]
        json_data["user_ids"].append(user_id)
        
        # Save to JSON file
        with open(json_file, "w", encoding="utf-8") as f:
          json.dump(json_data, f, ensure_ascii=False, indent=2)
        EOF
        
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Commit and push to main
      env:
        ENV__USER_PUBLIC_PATH: ${{ steps.extract.outputs.user_public_path }}
        ENV__USER_REGISTER_INFO_FILE: ${{ steps.env.outputs.user_register_info_file }}
        USER_ID: ${{ steps.extract.outputs.user_id }}
      run: |
        git checkout main
        git pull origin main
        git add "$ENV__USER_PUBLIC_PATH" "$ENV__USER_REGISTER_INFO_FILE" || true
        git commit -m "Add user directory for $USER_ID and registered user info" || echo "Nothing to commit"
        git push origin main
        
    - name: Comment on issue
      env:
        ENV__USER_SERVICE_PATH: ${{ steps.extract.outputs.user_service_path }}
        USER_ID: ${{ steps.extract.outputs.user_id }}
        REPO_NAME: ${{ github.event.repository.name }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "사용자 **$USER_ID** 등록 완료: [$REPO_NAME/$ENV__USER_SERVICE_PATH](https://$REPO_NAME/$ENV__USER_SERVICE_PATH)" > comment.md
        gh issue comment ${{ github.event.issue.number }} -F comment.md
