name: Deploy to cf-pages from main

on:
  workflow_dispatch: {}
      
jobs:
  merge-to-cf-pages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout cf-pages branch
      uses: actions/checkout@v3
      with:
        ref: cf-pages
        fetch-depth: 0
        
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Merge main into cf-pages branch
      run: |
        git fetch origin
        git merge origin/main -m "Merge main into cf-pages for deployment"
        git push origin cf-pages